// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3QfK_kyVbtBvsel3KnKkmG84Bz1O5PsA',
    appId: '1:423522306058:web:be5db3bb83fdb11eaf37f3',
    messagingSenderId: '423522306058',
    projectId: 'student-store-5253f',
    authDomain: 'student-store-5253f.firebaseapp.com',
    storageBucket: 'student-store-5253f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5V50AR7vDLFzHfN5XSfLwjRwMSOvtJY',
    appId: '1:423522306058:android:d5e0c387b5a893b5af37f3',
    messagingSenderId: '423522306058',
    projectId: 'student-store-5253f',
    storageBucket: 'student-store-5253f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqGzQ7Q2mqA8MaaK8l1bLv8KGcL7rv-oY',
    appId: '1:423522306058:ios:cd69e047a43f15feaf37f3',
    messagingSenderId: '423522306058',
    projectId: 'student-store-5253f',
    storageBucket: 'student-store-5253f.firebasestorage.app',
    iosBundleId: 'com.example.sclMgmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqGzQ7Q2mqA8MaaK8l1bLv8KGcL7rv-oY',
    appId: '1:423522306058:ios:cd69e047a43f15feaf37f3',
    messagingSenderId: '423522306058',
    projectId: 'student-store-5253f',
    storageBucket: 'student-store-5253f.firebasestorage.app',
    iosBundleId: 'com.example.sclMgmt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3QfK_kyVbtBvsel3KnKkmG84Bz1O5PsA',
    appId: '1:423522306058:web:503b3af58f60ab11af37f3',
    messagingSenderId: '423522306058',
    projectId: 'student-store-5253f',
    authDomain: 'student-store-5253f.firebaseapp.com',
    storageBucket: 'student-store-5253f.firebasestorage.app',
  );
}
